services:
  notifier:
    build: .
    container_name: notifier
    restart: unless-stopped
    environment:
      EWS_SERVER: ${EWS_SERVER}
      EWS_EMAIL: ${EWS_EMAIL}
      EWS_USERNAME: ${EWS_USERNAME}
      EWS_PASSWORD: ${EWS_PASSWORD}
      EWS_AUTH_TYPE: ${EWS_AUTH_TYPE}
      EWS_VERIFY_SSL: ${EWS_VERIFY_SSL}
      UPDATE_INTERVAL: ${UPDATE_INTERVAL}
      APPOINTMENT_REFRESH_INTERVAL: ${APPOINTMENT_REFRESH_INTERVAL}
      APPOINTMENT_NOTIFY_INTERVAL: ${APPOINTMENT_NOTIFY_INTERVAL}
      MAIL_REFRESH_INTERVAL: ${MAIL_REFRESH_INTERVAL}
      APPOINTMENT_BOT_TOKEN: ${APPOINTMENT_BOT_TOKEN}
      MAIL_BOT_TOKEN: ${MAIL_BOT_TOKEN}
      ALLOWED_CHAT_IDS: ${ALLOWED_CHAT_IDS}
      ADMIN_CHAT_ID: ${ADMIN_CHAT_ID}
      LOCAL_TIMEZONE: ${LOCAL_TIMEZONE}
      KEYWORDS: ${KEYWORDS}
      MENTION_TEXT: ${MENTION_TEXT}
      AGENDA_TIME: ${AGENDA_TIME}
      LOG_LEVEL: ${LOG_LEVEL}
